AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::GlobalAccelerator::CrossAccountAttachment resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.globalaccelerator.attachment.HandlerWrapper::handleRequest
      Runtime: java17
      CodeUri: ./target/aws-globalaccelerator-attacchment-handler-1.0-SNAPSHOT.jar
      MemorySize: 512

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.globalaccelerator.attachment.HandlerWrapper::testEntrypoint
      Runtime: java17
      CodeUri: ./target/aws-globalaccelerator-crossaccountattachment-handler-1.0-SNAPSHOT.jar
      MemorySize: 512
